package interpretador;

public enum TipoToken {

	IDENTIFICADOR,
	CONSTANTE_INTEIRA,
	CONSTANTE_FLOAT,
	ABRE_PARENTESES,	
	OPERADOR_RELACIONAL,
	OPERADOR_LOGICO,
	FIM_COMANDO,
	SEPARADOR_ARGUMENTO,
	TIPO_DADO,
	PALAVRA_RESERVADA,
	INICIO_ESCOPO,
	FIM_ESCOPO,
	FECHA_PARENTESES,
	OPERADOR_ARITMETICO,
	OPERADOR_ATRIBUICAO,
	INCREMENTO_DECREMENTO
}
