package interpretador_noturno;

public enum TipoToken {
	
	IDENTIFICADOR,
	CONSTANTE_INTEIRA,
	CONSTANTE_FLOAT,
	ABRE_PARENTESES,
	FECHA_PARENTESES,
	OPERADOR_ARITMETICO,
	OPERADOR_RELACIONAL,
	OPERADOR_LOGICO,
	FIM_COMANDO,
	SEPARADOR_ARGUMENTO,
	TIPO_DADO,
	PALAVRA_RESERVADA,
	INICIO_ESCOPO,
	FIM_ESCOPO,	
	OPERADOR_ATRIBUICAO,
	INCREMENTO_DECREMENTO,
	
}
